# Change these first
owner: formslogic # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository
assignees:
  - jhoelzel
  - fl-jhoelzel
sites:
  - name: Formslogic.com
    url: https://www.formslogic.com
  - name: Production
    url: $PRODUCTION_URL 
  - name: Production API
    url: $API_URL    
  - name: Staging
    url: $STAGING_URL 
  - name: New York Location IPv/6
    url: $NYC3_CLUSTER
    port: 443
    check: "tcp-ping"
    ipv6: true
  - name: New York Location IPv/4
    url: $NYC3_CLUSTER
    port: 443
    check: "tcp-ping"
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.formslogic.com
  theme: night 
  # baseUrl: /your-repo-name
  logoUrl: https://cdn.formslogicplatform.com/img/logos/formslogic_logo1_small.png
  name: Formslogic
  introTitle: "**Forms Logic** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Revolutionize your paperwork process with Forms Logic. Our digital platform for advisors streamlines client onboarding, enhances accuracy, and ensures compliance. Join the revolution today and experience efficiency like never before.
  navbar:
    - title: Status
      href: /
    - title: Formslogic.com
      href: https://www.Formslogic.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
commitMessages:
  commitAuthorName: "Formslogic-Bot"
  commitAuthorEmail: "status@formslogic.com"
  readmeContent: ":pencil: Update summary in README [skip ci] [upptime]"
  summaryJson: ":card_file_box: Update status summary [skip ci] [upptime]"
  statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms) [skip ci] [upptime]"
  graphsUpdate: ":bento: Update graphs [skip ci] [upptime]"
